### PR TITLE
Fixed typo and fixes #4

### LINKED ISSUE #4: Problem Selling on Latest Es_Extended
image

Using the latest Essentials Mode, and es_extended

### PR DESCRIPTION
**Pull request by M4ketech**
Fixed typo, and its fixing issue #4

### CODE REVIEW

**Comment by K3IDB** [comment]
not work for me

File: server/main.lua [hunk 1]
```diff
@@ -159,7 +159,7 @@ AddEventHandler('sellDrugs', function()
 	
 	xPlayer.addAccountMoney('black_money', blackMoney)
 	TriggerClientEvent('sold', _source)
-	TriggerClientEvent('esx:showNotification', _source, _U('you_have_sold') .. '~b~'..x..'~w~' .. _U(drugtype) .. blackMoney .. '$')
+	TriggerClientEvent('esx:showNotification', _source, _U('you_have_sold') .. '~b~'..x..'~w~' .. _U(drugType) .. blackMoney .. '$')
```
Comment (RikoDEV) [inline server/main.lua]: Should be:

`TriggerClientEvent('esx:showNotification', _source, _U('you_have_sold') .. '~b~'..x..'~w~ of '.. drugType ..' for ' .. blackMoney .. '$')`
